server:
  port: ${PORT:5005}

spring:
  application:
    name: taskManager

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false